version:'3'
services:
### Postgres database for invetory
db-inventory:
  container_name: db-inventory
  image: postgres:15.2
  restart: unless-stopped
  environment:
    POSTGRES_DB: ms_inventory
    POSTGRES_USER: robert
    POSTGRES_PASSWORD: robert123
  ports:
    - 5431:5431
  expose:
    - 5431
  command: -p 5431

  ### Postgres database for Orders
db-orders:
  container_name: db-orders
  image: mysql:8.0.33
  restart: unless-stopped
  environment:
    MYSQL_DATABASE: ms_orders
    MYSQL_USER: robert
    MYSQL_PASSWORD: robert123
    MYSQL_ROOT_PASSWORD: root
  ports:
    - 3306:3306
  expose:
    - 3306

### Postgres database for products
db-products:
  container_name: db-products
  image: postgres:15.2
  restart: unless-stopped
  environment:
    POSTGRES_DB: ms_products
    POSTGRES_USER: robert
    POSTGRES_PASSWORD: robert123
  ports:
    - 5432:5432
  expose:
    - 5432
  command: -p 5432